name: CI Trigger

on:
  push:
    branches:
      - main
    paths:
      - 'src/**' # Trigger pipeline only when files inside src/ change

permissions:
  contents: read
  packages: write

jobs:
  run-microservice-ci:
    uses: ./.github/workflows/microservice-ci.yaml
    permissions:
      contents: read
      packages: write
